chore: updated ggez version
* newer ggez is needed because:
  - wayland crashes due to outdated wgpu
  [wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.

  - there is alsa deps conflict
  error: multiple packages link to native library `alsa`, but a native library can be linked only once

package `alsa-sys v0.1.2`
    ... which satisfies dependency `alsa-sys = "^0.1"` (locked to 0.1.2) of package `cpal v0.8.2`
    ... which satisfies dependency `cpal = "^0.8"` (locked to 0.8.2) of package `rodio v0.9.0`
    ... which satisfies dependency `rodio = "^0.9"` (locked to 0.9.0) of package `ggez v0.5.1`
    ... which satisfies dependency `ggez = "^0.5.1"` (locked to 0.5.1) of package `crab_sweeper v0.1.0
links to native library `alsa`

package `alsa-sys v0.3.1`
    ... which satisfies dependency `alsa-sys = "^0.3.1"` (locked to 0.3.1) of package `alsa v0.5.0`
    ... which satisfies dependency `alsa = "^0.5"` (locked to 0.5.0) of package `cpal v0.13.3`
    ... which satisfies dependency `cpal = "^0.13"` (locked to 0.13.3) of package `rodio v0.13.1`
    ... which satisfies dependency `rodio = "^0.13"` (locked to 0.13.1) of package `crab_sweeper v0.1.0
also links to native library `alsa`